version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp-container
    ports:
      - '8080:8080'
    environment:
      - JWT_SECRET_KEY=!435tfrtretey
      - MONGO_URL=mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongo-data:
